services:
  mysql5:
    image: mysql:8.0.37-debian
    container_name: mysql5
    ports:
      - 3306:3306
    networks:
      - testNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_docker
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    build: 
      context: ./be
      dockerfile: Dockerfile
    image: annguyen2003/be:0.0.5
    container_name: be
    ports:
      - 8082:8082
    networks:
      - testNetwork
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql5:3306/test_docker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql5:
        condition: service_healthy

  an-food:
    build:
      context: ./an-food
      dockerfile: Dockerfile
    image: annguyen2003/an-food:0.0.5 
    container_name: an_food
    ports:
      - 5175:5175
    networks:
      - testNetwork
    depends_on:
      mysql5:
        condition: service_healthy

  admin-luan-food:
    build:
      context: ./admin-luan-food
      dockerfile: Dockerfile
    image: annguyen2003/admin-luan-food:0.0.5
    container_name: admin_luan_food
    ports:
      - 5176:5176
    networks:
      - testNetwork
    depends_on:
      mysql5:
        condition: service_healthy

networks:
  testNetwork:
    name: network5
