services:
  mysql4:
    image: mysql:latest
    container_name: mysql4
    ports:
      - 3306:3306
    networks:
      - testNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_docker
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    build: 
      context: ./be
      dockerfile: Dockerfile
    image: annguyen2003/be:0.0.4
    container_name: be
    ports:
      - 8081:8081
    networks:
      - testNetwork
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql4:3306/test_docker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql4:
        condition: service_healthy

  an-food:
    build:
      context: ./an-food
      dockerfile: Dockerfile
    image: annguyen2003/an-food:0.0.4 
    container_name: an-food
    ports:
      - "5173:5173"
    networks:
      - testNetwork
    depends_on:
      mysql4:
        condition: service_healthy

  admin-luan-food:
    build:
      context: ./admin-luan-food
      dockerfile: Dockerfile
    image: annguyen2003/admin-luan-food:0.0.4
    container_name: admin-luan-food
    ports:
      - "5174:5174"
    networks:
      - testNetwork
    depends_on:
      mysql4:
        condition: service_healthy

networks:
  testNetwork:
    name: network2
